title: >-
  Data to support network-wide 7-day ahead forecasting of water temperature in the Delaware River Basin: 3) model configurations

abstract: >-
  This data release contains the forcings and outputs of 7-day ahead maximum water temperature forecasting models
  that makes predictions at 70 river reaches in the upper Delaware River Basin. This section includes model
  parameters and metadata used to configure reservoir models.

cross-cites:
  -
    authors: ["Jacob A. Zwart", "Samantha K. Oliver", "David D. Watkins", "Jeffrey Sadler", "Alison P. Appling", "Hayley Corson-Dosch", "Xiaowei Jia", "Vipin Kumar", "Jordan Read"]
    title: >-
      XXSource code: Near-term forecasts of stream temperature using process-guided deep learning and data assimilation [UPDATE w/ link to zenodo]
    pubdate: 2022
    link: XX
  -
    authors: ['Matthew R. Hipsey', 'Louise C. Bruce', 'Casper Boon', 'Brendan Busch', 'Cayelan C. Carey', 'David P. Hamilton', 'Paul C. Hanson', 'Jordan S. Read', 'Eduardo de Sousa', 'Michael Weber', 'Luke A. Winslow']
    title: >-
      A General Lake Model (GLM 3.0) for linking with high-frequency sensor data from the Global Lake Ecological Observatory Network (GLEON).
    pubdate: 2019
    form: publication
    link: https://doi.org/10.5194/gmd-12-473-2019
  -
    authors: NA
    title: >-
      The General Lake Model - Configuration Options
    pubdate: 2019
    link: https://aed.see.uwa.edu.au/research/models/GLM/configuration.html

entities:
  -
    data-name: reservoir_nml_values.json
    data-description: >- 
      JSON file containing a nested list of reservoir parameters for input to GLM. 
      Top-level list elements are reservoirs, and fields within those elements are given as
      attributes below.
      Only Cannonsville and Pepacton Reservoir are included here. 
    attributes:
    -
      attr-label: site_id
      attr-def:  >-
        Reservoir identification number for this dataset. Is the Prmnn_I from NHD high-res prefixed with source, as "nhdhr_{Prmnn_I}"
      
        nhdhr_120022743 is Cannonsville Reservoir, nhdhr_151957878 is Pepacton Reservoir.
      attr-defs: http://nhd.usgs.gov/
      data-min: NA
      data-max: NA
      data-units: NA
    -
      attr-label: cd
      attr-def: >-
        Bulk aerodynamic transfer coefficient for momentum
      attr-defs: >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 0.001398495
      data-max: 0.001399558
      data-units: NA
    -
      attr-label: longitude
      attr-def: >-
        Longitude, positive East
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: -74.85719
      data-max: -75.30163
      data-units: decimal degrees
    -
      attr-label: latitude
      attr-def: >-
        Latitude, positive North
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 42.09106
      data-max: 42.09674
      data-units: decimal degrees
    -
      attr-label: bsn_wid 
      attr-def: >-
        Width of the lake basin, at crest height
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 4930.446
      data-max: 5432.168
      data-units: meters
    -
      attr-label: bsn_len
      attr-def: >-
        Length of the lake basin, at crest height
      attr-defs: >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 4930.446
      data-max: 5432.168
      data-units: meters
    -
      attr-label: lake_depth
      attr-def: >-
        Initial lake height/depth
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 48.7619
      data-max: 60.62472
      data-units: meters
    -
      attr-label: max_layer_thick
      attr-def: >-
        Maximum thickness of a layer 
      attr-defs: >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 1.5
      data-max: 1.5
      data-units: meters X 
    -
      attr-label: min_layer_thick
      attr-def: >-
        Minimum thickness of a layer 
      attr-defs: >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 0.2
      data-max: 0.2
      data-units: meters X 
    -
      attr-label: meteo_fl
      attr-def: >-
        Filename of the meteorological file
      attr-defs: >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: NA
      data-max: NA
      data-units: NA
    -
      attr-label: Kw
      attr-def: >-
        Light extinction coefficient
      attr-defs: >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 0.4613866
      data-max: 0.5617906
      data-units: per meter
    -
      attr-label: A
      attr-def: >-
        Comma-separated list of lake areas 
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 11.0551
      data-max: 25219560
      data-units: square meters
    -
      attr-label: H
      attr-def: >-
        Comma-separated list of lake elevations 
      attr-defs:  >-
        https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      data-min: 306.2021
      data-max: 394.3533
      data-units: meters
  -
    data-name: reservoir_nml_files.zip
    data-description: >-
      Zip file of complete .nml files, with calculated and calibrated parameters, as input to the 
      GLM runs that were used to produce the reservoir outlet predictions and DWALLIN dataset.
    attributes:
    -
      attr-label: >-
        glm3_cal_nhdhr_{}.nml
      attr-def:  >-
        Configuration file that specifies a GLM run. Formatting of the file, and values within each file, are as specified in the GLM documentation at https://aed.see.uwa.edu.au/research/models/GLM/configuration.html
      attr-defs: This data release
      data-min: NA
      data-max: NA
      data-units: NA


process-date: !expr format(Sys.time(),'%Y%m%d')
process-description: >-
  The General Lake Model (GLM) version 3.1 is a one-dimensional dynamical model which simplifies lakes using a vertical approximation,
  where horizontal variability is ignored. GLM uses a Lagrangian approach to layer structure where layers can split and combine based on changing vertical gradients.
  GLM is a modern implementation of other one-dimensional models.

indirect-spatial: U.S.A.
latitude-res: 0.1
longitude-res: 0.1
data-name: Model configuration details
data-description: >-
  Model configurations for running the General Lake Model (Hipsey and others 2019) version 3.1 for each lake.

file-format: JSON and zip files
